image: docker:stable

services:
  - docker:dind

stages:
  - build
  - test
  # - release
  # - deploy

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  CONTAINER_TEST_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH:latest

before_script:
  - docker login
    -u gitlab-ci-token
    -p $CI_JOB_TOKEN
    registry.gitlab.com
  - apk add --no-cache py-pip
  - pip install docker-compose

build:
  stage: build
  script:
    - docker pull $CONTAINER_RELEASE_IMAGE || true
    - docker build
      --tag $CONTAINER_TEST_IMAGE
      --tag $CONTAINER_RELEASE_IMAGE
      --cache-from $CONTAINER_RELEASE_IMAGE
      .
    - docker push $CONTAINER_TEST_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE

test:
  stage: test
  script:
    - docker-compose
      --file docker-compose.yml
      --file docker-compose.gitlab.yml
      run -e "RAILS_ENV=test" app bundle exec rspec spec
