version: '2'

services:
  app:
    build: ./
    env_file: .env
    command: bundle exec rails server -b 0.0.0.0
    volumes:
      - .:/listvytsia
      - ../data/db:/data/db
    ports:
      - 3005:3000
    networks:
      - dockernet
    depends_on:
      - db
  db:
    image: mongo:3.4.2
    # env_file: .env
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ../data/db:/data/db
    networks:
      - dockernet

networks:
  dockernet:
    external: false
