version: '2'

volumes:
  db-data:
    external: false

services:
  db:
    image: mongo:3.4.2
    env_file: .env
    volumes:
      - db-data:/var/lib/mongo/db-data
  app:
    build: ./
    env_file: .env
    volumes:
      - .:/listvytsia
    ports:
      - '3000:3000'
    depends_on:
      - db

