version: '2'

services:
  app:
    command: bundle exec rails server -b 0.0.0.0
    volumes:
      - ../data/db:/data/db
    ports:
      - 3000:3000
    networks:
      - dockernet
    depends_on:
      - db
  db:
    image: mongo:3.4.2
    volumes:
      - ../data/db:/data/db
    networks:
      - dockernet

networks:
  dockernet:
    external: false
