require 'rails'
require 'mongoid'
require 'mongoid_rails_migrations'
require 'pundit'
require 'devise'
require 'figaro'
require 'deface'
require 'rabl'
require 'slim-rails'
require 'require_all'

module Core; end

require_relative 'core/engine'
require_relative 'core/user_decorators'
require_relative 'core/application_policy'
require_relative 'core/base_presenter'
require_relative '../app/models/core/concerns/permalinkable'
require_relative 'core/social/base_adapter'
require_relative 'core/social/facebook_adapter'
require_relative 'core/social/google_adapter'
