test:
  clients:
    default:
      database: listvytsia_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
development:
  clients:
    default:
      database: listvytsia_development
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1

