development:
  clients:
    default:
      database: listvytsia_development
      hosts:
        - db:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
test:
  clients:
    default:
      database: listvytsia_test
      hosts:
        - db:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
production:
  clients:
    default:
      database: listvytsia_production
      hosts:
        - db:27017
      options:
        read:
          mode: :primary
        max_pool_size: 30
staging:
  clients:
    default:
      database: listvytsia_staging
      hosts:
        - db:27017
      options:
        read:
          mode: :primary
        max_pool_size: 2
