source 'https://rubygems.org'

gemspec

path '../' do
  gem 'pictures'
  gem 'seo_contents'
  gem 'core'
end

gem 'ckeditor',                 github: 'mkaszubowski/ckeditor',          ref: 'c9b5ea842222976c2d7f646f2d1210f4cb619fc2'
gem 'mongoid_rails_migrations', github: 'vbyno/mongoid_rails_migrations', ref: '0cacfa5b94e48b9eccc2ade56804d167c33ca1a3'
